---
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      # Security updates ignore this and are opened ad-hoc,
      # but this is still a required option.
      interval: daily
    # Prevent PRs from opening except for security updates
    open-pull-requests-limit: 0

  - package-ecosystem: npm
    directory: /apps/**/*
    schedule:
      interval: weekly
    open-pull-requests-limit: 0

  - package-ecosystem: npm
    directory: /packages/**/*
    schedule:
      interval: weekly
    open-pull-requests-limit: 0
